server:
  port: 8101
spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
sp:
  user-service:
    users: "[{\"id\":72, \"username\":\"abc\",\"password\":\"123\"},{\"id\":82, \"username\":\"def\",\"password\":\"456\"},{\"id\":92, \"username\":\"ghi\",\"password\":\"789\"}]"
eureka:
  client:
    service-url:
      defaultZone:  http://eureka1:2001/eureka,http://eureka2:2002/eureka 
management:
  endpoints:
    web:
      exposure:
        include: refresh   
